USE [master]
GO

/****** Object:  Database [EamonDemo]    Script Date: 5/10/2016 4:17:35 PM ******/
CREATE DATABASE [EamonDemo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EamonDemo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\EamonDemo.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'EamonDemo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\EamonDemo_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [EamonDemo] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EamonDemo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EamonDemo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EamonDemo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EamonDemo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EamonDemo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EamonDemo] SET ARITHABORT OFF 
GO

ALTER DATABASE [EamonDemo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EamonDemo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EamonDemo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EamonDemo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EamonDemo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EamonDemo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EamonDemo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EamonDemo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EamonDemo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EamonDemo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EamonDemo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EamonDemo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EamonDemo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EamonDemo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EamonDemo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EamonDemo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EamonDemo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EamonDemo] SET RECOVERY FULL 
GO

ALTER DATABASE [EamonDemo] SET  MULTI_USER 
GO

ALTER DATABASE [EamonDemo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EamonDemo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EamonDemo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EamonDemo] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [EamonDemo] SET  READ_WRITE 
GO


